services:
  omada-duckdns-updater:
    image: ghcr.io/kbipinkumar/omada-duckdns-updater:latest
    container_name: omada-duckdns-updater
    ports:
      - "5381:5381"
    environment:
      - DATA_DIR=/data
    volumes:
      # Use a named volume to persist configuration data independently of the Git repo (ideal for GitOps)
      - omada-data:/data
    restart: unless-stopped

volumes:
  omada-data:
