name: Build and Release
on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v' (e.g., v1.0.0)

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Upload Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to fetch all git tags for 'git describe'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.5'

      - name: Make scripts executable
        run: chmod +x build-deb.sh build-windows.sh

      - name: Build amd64 (Intel/AMD) Debian Package
        run: ./build-deb.sh amd64

      - name: Build arm64 (Raspberry Pi/ARM) Debian Package
        run: ./build-deb.sh arm64

      - name: Build Windows amd64 Zip
        run: ./build-windows.sh amd64

      - name: Build Windows arm64 Zip
        run: ./build-windows.sh arm64

      - name: Extract Tag Name
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            *_windows_*.zip
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
